### ISSUE TITLE
add ability to specify project with :TogglStart?

### ISSUE THREAD

**Issue by JonathanReeve** [termoshtt/toggl.vim#2]
First, thanks for making this plugin! It works great. It'd be really great if there were a way to run `:TogglStart some task here +projectName` and have the command start the task called "some task here" and assign it to the project 'projectName'. This would be really useful for users of todo.txt and todo.txt-vim, since todo.txt lines have entries like: 

```
make some breakfast +meals
```

Where the `+meals` is the project. If there were a way to specify the project name with `:TogglStart`, then I could put together some keybinding that runs `:TogglStart <current line here>`, and it would automatically start the task given by the current line in the todo.txt. That would be so awesome.

**Comment by termoshtt** [comment]
I create a PR #3 to resolve it.
Could you please test it?

**Comment by JonathanReeve** [comment]
Great! Starting a project works, with `:TogglStart task name +project`! I see you added tag specifiers too, that's so awesome. Starting a task with a tag doesn't yet work for me, though--I tried `:TogglStart test task @Coding`, for instance, and the task starts, but with the name 'test task @Coding' instead of attaching the tag Coding.

**Comment by JonathanReeve** [comment]
Nevermind, it looks like it's working now. Maybe I just forgot to reload it. Thanks! Closing.

**Comment by termoshtt** [comment]
Thanks!
